backend:
  name: git-gateway
  branch: master

media_folder: "dist/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "Title", widget: "string" }
