backend:
  name: git-gateway
  branch: master

media_library:
  name: cloudinary
  config:
    cloud_name: future-super
    api_key: 749866111487797 # Public Key

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "Title", widget: "string" }
